<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Mint.Workflow.Common\Mint.Workflow.Common.csproj"/>
        <ProjectReference Include="..\Mint.Workflow.Entity\Mint.Workflow.Entity.csproj"/>
        <ProjectReference Include="..\Mint.Workflow.Repository\Mint.Workflow.Repository.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="SyrianBallaS.AutoMapper.Extensions.Microsoft.DependencyInjection.Signed" Version="3.2.0"/>
    </ItemGroup>

</Project>
