-- ==============================================================
-- DBMS name:      PostgreSQL 15+
-- Created on:     2026/08/02 17:15:03
-- ==============================================================

-- 删除已存在的表（级联删除依赖）
DROP TABLE IF EXISTS mk_workflowsql CASCADE;
DROP TABLE IF EXISTS mk_workflow_urge CASCADE;
DROP TABLE IF EXISTS mk_workflow_transition_history CASCADE;
DROP TABLE IF EXISTS mk_workflow_operation_history CASCADE;
DROP TABLE IF EXISTS mk_workflow_notice CASCADE;
DROP TABLE IF EXISTS mk_workflow_instance_form CASCADE;
DROP TABLE IF EXISTS mk_workflow_instance CASCADE;
DROP TABLE IF EXISTS mk_workflow_form CASCADE;
DROP TABLE IF EXISTS mk_workflow_category CASCADE;
DROP TABLE IF EXISTS mk_workflow_assign CASCADE;
DROP TABLE IF EXISTS mk_workflow CASCADE;
DROP TABLE IF EXISTS mk_user_role CASCADE;
DROP TABLE IF EXISTS mk_user_dept CASCADE;
DROP TABLE IF EXISTS mk_user CASCADE;
DROP TABLE IF EXISTS mk_role_resource CASCADE;
DROP TABLE IF EXISTS mk_role CASCADE;
DROP TABLE IF EXISTS mk_resource CASCADE;
DROP TABLE IF EXISTS mk_dept CASCADE;
DROP TABLE IF EXISTS mk_systems CASCADE;

-- ==============================================================
-- Table: mk_systems
-- ==============================================================
CREATE TABLE mk_systems (
    "SystemId"     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SystemName"   VARCHAR(255),
    "SystemCode"   VARCHAR(255),
    "IsDel"        BOOLEAN,
    "Memo"         VARCHAR(255),
    "Sort"         INT,
    "CreateTime"   BIGINT,
    "CreateUserId" BIGINT,
    "UpdateTime"   BIGINT
);

COMMENT ON TABLE mk_systems IS '系统模块';
COMMENT ON COLUMN mk_systems."SystemId" IS '系统ID';
COMMENT ON COLUMN mk_systems."SystemName" IS '系统名称';
COMMENT ON COLUMN mk_systems."SystemCode" IS '系统编码';
COMMENT ON COLUMN mk_systems."IsDel" IS '是否删除 1:是，0:否';
COMMENT ON COLUMN mk_systems."Memo" IS '备注';
COMMENT ON COLUMN mk_systems."Sort" IS '排序';
COMMENT ON COLUMN mk_systems."CreateTime" IS '创建时间戳';
COMMENT ON COLUMN mk_systems."CreateUserId" IS '创建人ID';
COMMENT ON COLUMN mk_systems."UpdateTime" IS '更新时间戳';

-- ==============================================================
-- Table: mk_dept
-- ==============================================================
CREATE TABLE mk_dept (
    "DeptId"       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SystemId"     BIGINT,
    "DeptName"     VARCHAR(255),
    "DeptCode"     VARCHAR(255),
    "ParentId"     BIGINT,
    "Path"         VARCHAR(255),
    "IsDel"        BOOLEAN,
    "Memo"         VARCHAR(255),
    "CreateUserId" BIGINT,
    "CreateTime"   BIGINT
);

COMMENT ON TABLE mk_dept IS '部门模块';
COMMENT ON COLUMN mk_dept."DeptId" IS '部门ID';
COMMENT ON COLUMN mk_dept."SystemId" IS '系统ID';
COMMENT ON COLUMN mk_dept."DeptName" IS '部门名称';
COMMENT ON COLUMN mk_dept."DeptCode" IS '部门编码';
COMMENT ON COLUMN mk_dept."ParentId" IS '父级ID';
COMMENT ON COLUMN mk_dept."Path" IS '路径';
COMMENT ON COLUMN mk_dept."IsDel" IS '是否删除 1:是，0:否';
COMMENT ON COLUMN mk_dept."Memo" IS '备注';
COMMENT ON COLUMN mk_dept."CreateUserId" IS '创建人ID';
COMMENT ON COLUMN mk_dept."CreateTime" IS '创建时间戳';

-- ==============================================================
-- Table: mk_resource
-- ==============================================================
CREATE TABLE mk_resource (
    "ResourceId"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SystemId"     BIGINT,
    "ResourceName" VARCHAR(255),
    "ParentId"     BIGINT,
    "ResourceUrl"  VARCHAR(255),
    "Sort"         INT,
    "ButtonClass"  VARCHAR(255),
    "Icon"         VARCHAR(255),
    "IsShow"       BOOLEAN,
    "CreateUserId" BIGINT,
    "CreateTime"   BIGINT,
    "IsDel"        BOOLEAN,
    "Memo"         VARCHAR(255),
    "IsButton"     BOOLEAN,
    "ButtonType"   BOOLEAN,
    "Path"         VARCHAR(255)
);

COMMENT ON TABLE mk_resource IS '资源（菜单）模块';
COMMENT ON COLUMN mk_resource."ResourceId" IS '资源ID';
COMMENT ON COLUMN mk_resource."SystemId" IS '系统ID';
COMMENT ON COLUMN mk_resource."ResourceName" IS '资源名称';
COMMENT ON COLUMN mk_resource."ParentId" IS '父级ID';
COMMENT ON COLUMN mk_resource."ResourceUrl" IS '资源URL';
COMMENT ON COLUMN mk_resource."Sort" IS '排序';
COMMENT ON COLUMN mk_resource."ButtonClass" IS '按钮样式';
COMMENT ON COLUMN mk_resource."Icon" IS '图标';
COMMENT ON COLUMN mk_resource."IsShow" IS '是否显示';
COMMENT ON COLUMN mk_resource."CreateUserId" IS '创建人ID';
COMMENT ON COLUMN mk_resource."CreateTime" IS '创建时间戳';
COMMENT ON COLUMN mk_resource."IsDel" IS '是否删除';
COMMENT ON COLUMN mk_resource."Memo" IS '备注';
COMMENT ON COLUMN mk_resource."IsButton" IS '是否为按钮';
COMMENT ON COLUMN mk_resource."ButtonType" IS '按钮类型';
COMMENT ON COLUMN mk_resource."Path" IS '路径';

-- ==============================================================
-- Table: mk_role
-- ==============================================================
CREATE TABLE mk_role (
    "RoleId"       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SystemId"     BIGINT,
    "RoleName"     VARCHAR(255),
    "Memo"         VARCHAR(255),
    "IsDel"        BOOLEAN,
    "CreateUserId" BIGINT,
    "CreateTime"   BIGINT,
    "UpdateUserId" BIGINT,
    "UpdateTime"   BIGINT
);

COMMENT ON TABLE mk_role IS '角色模块';
COMMENT ON COLUMN mk_role."RoleId" IS '角色ID';
COMMENT ON COLUMN mk_role."SystemId" IS '系统ID';
COMMENT ON COLUMN mk_role."RoleName" IS '角色名称';
COMMENT ON COLUMN mk_role."Memo" IS '备注';
COMMENT ON COLUMN mk_role."IsDel" IS '是否删除';
COMMENT ON COLUMN mk_role."CreateUserId" IS '创建人ID';
COMMENT ON COLUMN mk_role."CreateTime" IS '创建时间戳';
COMMENT ON COLUMN mk_role."UpdateUserId" IS '修改人ID';
COMMENT ON COLUMN mk_role."UpdateTime" IS '修改时间戳';

-- ==============================================================
-- Table: mk_role_resource
-- ==============================================================
CREATE TABLE mk_role_resource (
    "Id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RoleId"       BIGINT,
    "ResourceId"   BIGINT,
    "CreateTime"   BIGINT
);

COMMENT ON TABLE mk_role_resource IS '角色资源关联模块';
COMMENT ON COLUMN mk_role_resource."Id" IS '关联ID';
COMMENT ON COLUMN mk_role_resource."RoleId" IS '角色ID';
COMMENT ON COLUMN mk_role_resource."ResourceId" IS '资源ID';
COMMENT ON COLUMN mk_role_resource."CreateTime" IS '创建时间戳';

-- ==============================================================
-- Table: mk_user
-- ==============================================================
CREATE TABLE mk_user (
    "UserId"       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SystemId"     BIGINT,
    "Account"      VARCHAR(255),
    "UserName"     VARCHAR(255),
    "JobNumber"    VARCHAR(255),
    "Password"     VARCHAR(255),
    "HeadImg"      VARCHAR(255),
    "IsDel"        BOOLEAN,
    "CreateUserId" BIGINT,
    "CreateTime"   BIGINT,
    "UpdateUserId" BIGINT,
    "UpdateTime"   BIGINT
);

COMMENT ON TABLE mk_user IS '用户模块';
COMMENT ON COLUMN mk_user."UserId" IS '用户ID';
COMMENT ON COLUMN mk_user."SystemId" IS '系统ID';
COMMENT ON COLUMN mk_user."Account" IS '账号';
COMMENT ON COLUMN mk_user."UserName" IS '用户名称';
COMMENT ON COLUMN mk_user."JobNumber" IS '工号';
COMMENT ON COLUMN mk_user."Password" IS '密码';
COMMENT ON COLUMN mk_user."HeadImg" IS '头像地址';
COMMENT ON COLUMN mk_user."IsDel" IS '是否删除 1:是，0:否';
COMMENT ON COLUMN mk_user."CreateUserId" IS '创建人ID';
COMMENT ON COLUMN mk_user."CreateTime" IS '创建时间戳';
COMMENT ON COLUMN mk_user."UpdateUserId" IS '修改人ID';
COMMENT ON COLUMN mk_user."UpdateTime" IS '修改时间戳';

-- ==============================================================
-- Table: mk_user_dept
-- ==============================================================
CREATE TABLE mk_user_dept (
    "Id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"       BIGINT,
    "DeptId"       BIGINT,
    "CreateTime"   BIGINT
);

COMMENT ON TABLE mk_user_dept IS '用户部门关联模块';
COMMENT ON COLUMN mk_user_dept."Id" IS '关联ID';
COMMENT ON COLUMN mk_user_dept."UserId" IS '用户ID';
COMMENT ON COLUMN mk_user_dept."DeptId" IS '部门ID';
COMMENT ON COLUMN mk_user_dept."CreateTime" IS '创建时间戳';

-- ==============================================================
-- Table: mk_user_role
-- ==============================================================
CREATE TABLE mk_user_role (
    "Id"           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"       BIGINT,
    "RoleId"       BIGINT,
    "CreateTime"   BIGINT
);

COMMENT ON TABLE mk_user_role IS '用户角色关联模块';
COMMENT ON COLUMN mk_user_role."Id" IS '关联ID';
COMMENT ON COLUMN mk_user_role."UserId" IS '用户ID';
COMMENT ON COLUMN mk_user_role."RoleId" IS '角色ID';
COMMENT ON COLUMN mk_user_role."CreateTime" IS '创建时间戳';

-- ==============================================================
-- Table: mk_workflow_category
-- ==============================================================
CREATE TABLE mk_workflow_category (
    "CategoryId"   VARCHAR(50) PRIMARY KEY,
    "Name"         VARCHAR(255),
    "ParentId"     VARCHAR(255),
    "Memo"         VARCHAR(255),
    "Status"       INT,
    "CreateUserId" VARCHAR(255),
    "CreateTime"   BIGINT
);

COMMENT ON TABLE mk_workflow_category IS '流程分类模块';
COMMENT ON COLUMN mk_workflow_category."CategoryId" IS '分类ID';
COMMENT ON COLUMN mk_workflow_category."Name" IS '分类名称';
COMMENT ON COLUMN mk_workflow_category."ParentId" IS '父级ID';
COMMENT ON COLUMN mk_workflow_category."Memo" IS '备注';
COMMENT ON COLUMN mk_workflow_category."Status" IS '状态';
COMMENT ON COLUMN mk_workflow_category."CreateUserId" IS '创建人ID';
COMMENT ON COLUMN mk_workflow_category."CreateTime" IS '创建时间戳';

-- ==============================================================
-- Table: mk_workflow_form
-- ==============================================================
CREATE TABLE mk_workflow_form (
    "FormId"           VARCHAR(255) PRIMARY KEY,
    "FormName"         VARCHAR(255),
    "FormType"         INT,
    "Content"          TEXT,
    "OriginalContent"  TEXT,
    "FormUrl"          VARCHAR(255),
    "CreateUserId"     VARCHAR(255),
    "CreateTime"       BIGINT
);

COMMENT ON TABLE mk_workflow_form IS '流程表单模块';
COMMENT ON COLUMN mk_workflow_form."FormId" IS '表单ID';
COMMENT ON COLUMN mk_workflow_form."FormName" IS '表单名称';
COMMENT ON COLUMN mk_workflow_form."FormType" IS '表单类型';
COMMENT ON COLUMN mk_workflow_form."Content" IS '表单内容（JSON）';
COMMENT ON COLUMN mk_workflow_form."OriginalContent" IS '原始内容';
COMMENT ON COLUMN mk_workflow_form."FormUrl" IS '表单URL';
COMMENT ON COLUMN mk_workflow_form."CreateUserId" IS '创建人ID';
COMMENT ON COLUMN mk_workflow_form."CreateTime" IS '创建时间戳';

-- ==============================================================
-- Table: mk_workflow
-- ==============================================================
CREATE TABLE mk_workflow (
    "FlowId"       VARCHAR(50) PRIMARY KEY,
    "FlowCode"     VARCHAR(255),
    "CategoryId"   VARCHAR(255),
    "FormId"       VARCHAR(255),
    "FlowName"     VARCHAR(255),
    "FlowContent"  TEXT,
    "FlowVersion"  INT,
    "Memo"         VARCHAR(255),
    "Enable"       INT,
    "IsOld"        INT,
    "CreateUserId" VARCHAR(50),
    "CreateTime"   BIGINT
);

COMMENT ON TABLE mk_workflow IS '流程定义模块';
COMMENT ON COLUMN mk_workflow."FlowId" IS '流程ID';
COMMENT ON COLUMN mk_workflow."FlowCode" IS '流程编码';
COMMENT ON COLUMN mk_workflow."CategoryId" IS '分类ID';
COMMENT ON COLUMN mk_workflow."FormId" IS '表单ID';
COMMENT ON COLUMN mk_workflow."FlowName" IS '流程名称';
COMMENT ON COLUMN mk_workflow."FlowContent" IS '流程JSON内容';
COMMENT ON COLUMN mk_workflow."FlowVersion" IS '流程版本（默认1）';
COMMENT ON COLUMN mk_workflow."Memo" IS '备注';
COMMENT ON COLUMN mk_workflow."Enable" IS '是否启用 1:启用，0:禁用';
COMMENT ON COLUMN mk_workflow."IsOld" IS '是否旧版本';
COMMENT ON COLUMN mk_workflow."CreateUserId" IS '创建人ID';
COMMENT ON COLUMN mk_workflow."CreateTime" IS '创建时间戳';

-- ==============================================================
-- Table: mk_workflow_instance
-- ==============================================================
CREATE TABLE mk_workflow_instance (
    "InstanceId"     VARCHAR(255) PRIMARY KEY,
    "FlowId"         VARCHAR(255),
    "Code"           VARCHAR(255),
    "ActivityId"     VARCHAR(255),
    "ActivityType"   INT,
    "ActivityName"   VARCHAR(255),
    "PreviousId"     VARCHAR(255),
    "MakerList"      VARCHAR(255),
    "FlowContent"    TEXT,
    "FlowVersion"    INT,
    "CreateUserName" VARCHAR(255),
    "UpdateTime"     BIGINT,
    "CreateUserId"   VARCHAR(255),
    "CreateTime"     BIGINT
);

COMMENT ON TABLE mk_workflow_instance IS '流程实例模块（运行中的流程）';
COMMENT ON COLUMN mk_workflow_instance."InstanceId" IS '实例ID';
COMMENT ON COLUMN mk_workflow_instance."FlowId" IS '流程ID';
COMMENT ON COLUMN mk_workflow_instance."Code" IS '实例编号';
COMMENT ON COLUMN mk_workflow_instance."ActivityId" IS '当前节点ID';
COMMENT ON COLUMN mk_workflow_instance."ActivityType" IS '当前节点类型';
COMMENT ON COLUMN mk_workflow_instance."ActivityName" IS '当前节点名称';
COMMENT ON COLUMN mk_workflow_instance."PreviousId" IS '上一节点ID';
COMMENT ON COLUMN mk_workflow_instance."MakerList" IS '执行人（0表示全部）';
COMMENT ON COLUMN mk_workflow_instance."FlowContent" IS '流程JSON内容（快照）';
COMMENT ON COLUMN mk_workflow_instance."FlowVersion" IS '流程版本';
COMMENT ON COLUMN mk_workflow_instance."CreateUserName" IS '创建人名称';
COMMENT ON COLUMN mk_workflow_instance."UpdateTime" IS '更新时间戳';
COMMENT ON COLUMN mk_workflow_instance."CreateUserId" IS '创建人ID';
COMMENT ON COLUMN mk_workflow_instance."CreateTime" IS '创建时间戳';

-- ==============================================================
-- Table: mk_workflow_assign
-- ==============================================================
CREATE TABLE mk_workflow_assign (
    "AssignId"       VARCHAR(255) PRIMARY KEY,
    "FlowId"         VARCHAR(255),
    "InstanceId"     VARCHAR(255),
    "NodeId"         VARCHAR(255),
    "NodeName"       VARCHAR(255),
    "UserId"         VARCHAR(255),
    "UserName"       VARCHAR(255),
    "AssignUserId"   VARCHAR(255),
    "AssignUserName" VARCHAR(255),
    "Content"        VARCHAR(255),
    "CreateUserId"   VARCHAR(255),
    "CreateTime"     BIGINT
);

COMMENT ON TABLE mk_workflow_assign IS '流程委托模块';
COMMENT ON COLUMN mk_workflow_assign."AssignId" IS '委托ID';
COMMENT ON COLUMN mk_workflow_assign."FlowId" IS '流程ID';
COMMENT ON COLUMN mk_workflow_assign."InstanceId" IS '实例ID';
COMMENT ON COLUMN mk_workflow_assign."NodeId" IS '节点ID';
COMMENT ON COLUMN mk_workflow_assign."NodeName" IS '节点名称';
COMMENT ON COLUMN mk_workflow_assign."UserId" IS '委托人ID';
COMMENT ON COLUMN mk_workflow_assign."UserName" IS '委托人名称';
COMMENT ON COLUMN mk_workflow_assign."AssignUserId" IS '被委托人ID';
COMMENT ON COLUMN mk_workflow_assign."AssignUserName" IS '被委托人名称';
COMMENT ON COLUMN mk_workflow_assign."Content" IS '委托内容';
COMMENT ON COLUMN mk_workflow_assign."CreateUserId" IS '创建人ID';
COMMENT ON COLUMN mk_workflow_assign."CreateTime" IS '创建时间戳';

-- ==============================================================
-- Table: mk_workflow_instance_form
-- ==============================================================
CREATE TABLE mk_workflow_instance_form (
    "InstanceFormId" VARCHAR(255) PRIMARY KEY,
    "InstanceId"     VARCHAR(255),
    "FormId"         VARCHAR(255),
    "FlowContent"    TEXT,
    "FormType"       INT,
    "FormUrl"        VARCHAR(255),
    "FormData"       TEXT,
    "CreateUserId"   VARCHAR(255),
    "CreateTime"     BIGINT
);

COMMENT ON TABLE mk_workflow_instance_form IS '流程实例表单数据模块';
COMMENT ON COLUMN mk_workflow_instance_form."InstanceFormId" IS '实例表单ID';
COMMENT ON COLUMN mk_workflow_instance_form."InstanceId" IS '实例ID';
COMMENT ON COLUMN mk_workflow_instance_form."FormId" IS '表单ID';
COMMENT ON COLUMN mk_workflow_instance_form."FlowContent" IS '流程JSON内容';
COMMENT ON COLUMN mk_workflow_instance_form."FormType" IS '表单类型';
COMMENT ON COLUMN mk_workflow_instance_form."FormUrl" IS '表单URL';
COMMENT ON COLUMN mk_workflow_instance_form."FormData" IS '表单数据（JSON）';
COMMENT ON COLUMN mk_workflow_instance_form."CreateUserId" IS '创建人ID';
COMMENT ON COLUMN mk_workflow_instance_form."CreateTime" IS '创建时间戳';

-- ==============================================================
-- Table: mk_workflow_notice
-- ==============================================================
CREATE TABLE mk_workflow_notice (
    "NoticeId"     VARCHAR(255) PRIMARY KEY,
    "InstanceId"   VARCHAR(255),
    "NodeId"       VARCHAR(255),
    "NodeName"     VARCHAR(255),
    "Maker"        VARCHAR(255),
    "IsTransition" BOOLEAN,
    "Status"       BOOLEAN,
    "IsRead"       BOOLEAN,
    "CreateUserId" VARCHAR(255),
    "CreateTime"   BIGINT
);

COMMENT ON TABLE mk_workflow_notice IS '流程通知节点模块';
COMMENT ON COLUMN mk_workflow_notice."NoticeId" IS '通知ID';
COMMENT ON COLUMN mk_workflow_notice."InstanceId" IS '实例ID';
COMMENT ON COLUMN mk_workflow_notice."NodeId" IS '节点ID';
COMMENT ON COLUMN mk_workflow_notice."NodeName" IS '节点名称';
COMMENT ON COLUMN mk_workflow_notice."Maker" IS '执行人';
COMMENT ON COLUMN mk_workflow_notice."IsTransition" IS '是否可转交';
COMMENT ON COLUMN mk_workflow_notice."Status" IS '状态';
COMMENT ON COLUMN mk_workflow_notice."IsRead" IS '是否已读';
COMMENT ON COLUMN mk_workflow_notice."CreateUserId" IS '创建人ID';
COMMENT ON COLUMN mk_workflow_notice."CreateTime" IS '创建时间戳';

-- ==============================================================
-- Table: mk_workflow_operation_history
-- ==============================================================
CREATE TABLE mk_workflow_operation_history (
    "OperationId"    VARCHAR(255) PRIMARY KEY,
    "InstanceId"     VARCHAR(255),
    "NodeId"         VARCHAR(255),
    "NodeName"       VARCHAR(255),
    "TransitionType" INT,
    "Content"        VARCHAR(255),
    "CreateUserName" VARCHAR(255),
    "CreateUserId"   VARCHAR(255),
    "CreateTime"     BIGINT
);

COMMENT ON TABLE mk_workflow_operation_history IS '流程操作历史模块';
COMMENT ON COLUMN mk_workflow_operation_history."OperationId" IS '操作记录ID';
COMMENT ON COLUMN mk_workflow_operation_history."InstanceId" IS '实例ID';
COMMENT ON COLUMN mk_workflow_operation_history."NodeId" IS '节点ID';
COMMENT ON COLUMN mk_workflow_operation_history."NodeName" IS '节点名称';
COMMENT ON COLUMN mk_workflow_operation_history."TransitionType" IS '转交类型';
COMMENT ON COLUMN mk_workflow_operation_history."Content" IS '操作内容';
COMMENT ON COLUMN mk_workflow_operation_history."CreateUserName" IS '操作人名称';
COMMENT ON COLUMN mk_workflow_operation_history."CreateUserId" IS '操作人ID';
COMMENT ON COLUMN mk_workflow_operation_history."CreateTime" IS '操作时间戳';

-- ==============================================================
-- Table: mk_workflow_transition_history
-- ==============================================================
CREATE TABLE mk_workflow_transition_history (
    "TransitionId"   VARCHAR(255) PRIMARY KEY,
    "InstanceId"     VARCHAR(255),
    "FromNodeId"     VARCHAR(255),
    "FromNodeType"   INT,
    "FromNodName"    VARCHAR(255),
    "ToNodeId"       VARCHAR(255),
    "ToNodeType"     INT,
    "ToNodeName"     VARCHAR(255),
    "TransitionState" INT,
    "IsFinish"       INT,
    "CreateUserName" VARCHAR(255),
    "CreateUserId"   VARCHAR(255),
    "CreateTime"     BIGINT
);

COMMENT ON TABLE mk_workflow_transition_history IS '流程转交历史模块';
COMMENT ON COLUMN mk_workflow_transition_history."TransitionId" IS '转交记录ID';
COMMENT ON COLUMN mk_workflow_transition_history."InstanceId" IS '实例ID';
COMMENT ON COLUMN mk_workflow_transition_history."FromNodeId" IS '来源节点ID';
COMMENT ON COLUMN mk_workflow_transition_history."FromNodeType" IS '来源节点类型';
COMMENT ON COLUMN mk_workflow_transition_history."FromNodName" IS '来源节点名称';
COMMENT ON COLUMN mk_workflow_transition_history."ToNodeId" IS '目标节点ID';
COMMENT ON COLUMN mk_workflow_transition_history."ToNodeType" IS '目标节点类型';
COMMENT ON COLUMN mk_workflow_transition_history."ToNodeName" IS '目标节点名称';
COMMENT ON COLUMN mk_workflow_transition_history."TransitionState" IS '转交状态';
COMMENT ON COLUMN mk_workflow_transition_history."IsFinish" IS '是否结束';
COMMENT ON COLUMN mk_workflow_transition_history."CreateUserName" IS '创建人名称';
COMMENT ON COLUMN mk_workflow_transition_history."CreateUserId" IS '创建人ID';
COMMENT ON COLUMN mk_workflow_transition_history."CreateTime" IS '创建时间戳';

-- ==============================================================
-- Table: mk_workflow_urge
-- ==============================================================
CREATE TABLE mk_workflow_urge (
    "UrgeId"       VARCHAR(255) PRIMARY KEY,
    "InstanceId"   VARCHAR(255),
    "NodeId"       VARCHAR(255),
    "NodeName"     VARCHAR(255),
    "Sender"       VARCHAR(255),
    "UrgeUser"     VARCHAR(255),
    "UrgeType"     INT,
    "UrgeContent"  VARCHAR(255),
    "CreateUserId" VARCHAR(255),
    "CreateTime"   BIGINT
);

COMMENT ON TABLE mk_workflow_urge IS '流程催办模块';
COMMENT ON COLUMN mk_workflow_urge."UrgeId" IS '催办ID';
COMMENT ON COLUMN mk_workflow_urge."InstanceId" IS '实例ID';
COMMENT ON COLUMN mk_workflow_urge."NodeId" IS '节点ID';
COMMENT ON COLUMN mk_workflow_urge."NodeName" IS '节点名称';
COMMENT ON COLUMN mk_workflow_urge."Sender" IS '发送人';
COMMENT ON COLUMN mk_workflow_urge."UrgeUser" IS '催办对象';
COMMENT ON COLUMN mk_workflow_urge."UrgeType" IS '催办类型';
COMMENT ON COLUMN mk_workflow_urge."UrgeContent" IS '催办内容';
COMMENT ON COLUMN mk_workflow_urge."CreateUserId" IS '创建人ID';
COMMENT ON COLUMN mk_workflow_urge."CreateTime" IS '创建时间戳';

-- ==============================================================
-- Table: mk_workflowsql
-- ==============================================================
CREATE TABLE mk_workflowsql (
    "Name"         VARCHAR(255) PRIMARY KEY,
    "FlowId"       VARCHAR(50),
    "FlowSQL"      VARCHAR(255),
    "Param"        VARCHAR(255),
    "SQLType"      BOOLEAN,
    "Status"       INT,
    "Remark"       VARCHAR(255),
    "CreateUserId" BIGINT,
    "CreateTime"   BIGINT
);

COMMENT ON TABLE mk_workflowsql IS '流程外部SQL权限模块';
COMMENT ON COLUMN mk_workflowsql."Name" IS '名称（主键）';
COMMENT ON COLUMN mk_workflowsql."FlowId" IS '流程ID';
COMMENT ON COLUMN mk_workflowsql."FlowSQL" IS 'SQL语句';
COMMENT ON COLUMN mk_workflowsql."Param" IS '参数';
COMMENT ON COLUMN mk_workflowsql."SQLType" IS 'SQL类型';
COMMENT ON COLUMN mk_workflowsql."Status" IS '状态';
COMMENT ON COLUMN mk_workflowsql."Remark" IS '备注';
COMMENT ON COLUMN mk_workflowsql."CreateUserId" IS '创建人ID';
COMMENT ON COLUMN mk_workflowsql."CreateTime" IS '创建时间戳';

-- ==============================================================
-- 外键约束（按依赖顺序添加）
-- ==============================================================
ALTER TABLE mk_dept ADD CONSTRAINT fk_mk_dept_system FOREIGN KEY ("SystemId") REFERENCES mk_systems ("SystemId");

ALTER TABLE mk_resource ADD CONSTRAINT fk_mk_resource_system FOREIGN KEY ("SystemId") REFERENCES mk_systems ("SystemId");

ALTER TABLE mk_role ADD CONSTRAINT fk_mk_role_system FOREIGN KEY ("SystemId") REFERENCES mk_systems ("SystemId");

ALTER TABLE mk_role_resource ADD CONSTRAINT fk_mk_role_resource_role FOREIGN KEY ("RoleId") REFERENCES mk_role ("RoleId");
ALTER TABLE mk_role_resource ADD CONSTRAINT fk_mk_role_resource_resource FOREIGN KEY ("ResourceId") REFERENCES mk_resource ("ResourceId");

ALTER TABLE mk_user ADD CONSTRAINT fk_mk_user_system FOREIGN KEY ("SystemId") REFERENCES mk_systems ("SystemId");

ALTER TABLE mk_user_dept ADD CONSTRAINT fk_mk_user_dept_dept FOREIGN KEY ("DeptId") REFERENCES mk_dept ("DeptId");
ALTER TABLE mk_user_dept ADD CONSTRAINT fk_mk_user_dept_user FOREIGN KEY ("UserId") REFERENCES mk_user ("UserId");

ALTER TABLE mk_user_role ADD CONSTRAINT fk_mk_user_role_user FOREIGN KEY ("UserId") REFERENCES mk_user ("UserId");
ALTER TABLE mk_user_role ADD CONSTRAINT fk_mk_user_role_role FOREIGN KEY ("RoleId") REFERENCES mk_role ("RoleId");

ALTER TABLE mk_workflow ADD CONSTRAINT fk_mk_workflow_category FOREIGN KEY ("CategoryId") REFERENCES mk_workflow_category ("CategoryId");
ALTER TABLE mk_workflow ADD CONSTRAINT fk_mk_workflow_form FOREIGN KEY ("FormId") REFERENCES mk_workflow_form ("FormId");

ALTER TABLE mk_workflow_instance ADD CONSTRAINT fk_mk_workflow_instance_workflow FOREIGN KEY ("FlowId") REFERENCES mk_workflow ("FlowId");

ALTER TABLE mk_workflow_assign ADD CONSTRAINT fk_mk_workflow_assign_instance FOREIGN KEY ("InstanceId") REFERENCES mk_workflow_instance ("InstanceId");

ALTER TABLE mk_workflow_instance_form ADD CONSTRAINT fk_mk_workflow_instance_form_form FOREIGN KEY ("FormId") REFERENCES mk_workflow_form ("FormId");
ALTER TABLE mk_workflow_instance_form ADD CONSTRAINT fk_mk_workflow_instance_form_instance FOREIGN KEY ("InstanceId") REFERENCES mk_workflow_instance ("InstanceId");

ALTER TABLE mk_workflow_notice ADD CONSTRAINT fk_mk_workflow_notice_instance FOREIGN KEY ("InstanceId") REFERENCES mk_workflow_instance ("InstanceId");

ALTER TABLE mk_workflow_operation_history ADD CONSTRAINT fk_mk_workflow_operation_history_instance FOREIGN KEY ("InstanceId") REFERENCES mk_workflow_instance ("InstanceId");

ALTER TABLE mk_workflow_transition_history ADD CONSTRAINT fk_mk_workflow_transition_history_instance FOREIGN KEY ("InstanceId") REFERENCES mk_workflow_instance ("InstanceId");

ALTER TABLE mk_workflow_urge ADD CONSTRAINT fk_mk_workflow_urge_instance FOREIGN KEY ("InstanceId") REFERENCES mk_workflow_instance ("InstanceId");

ALTER TABLE mk_workflowsql ADD CONSTRAINT fk_mk_workflowsql_workflow FOREIGN KEY ("FlowId") REFERENCES mk_workflow ("FlowId");
